<a href="https://colab.research.google.com/github/iiLolaii/data-management-262/blob/main/g_drive_script_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Data Management - Final/dm_script_test.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,doi,title,authors,journal_name,publication_year,primary_sources,secondary_sources,geographic_location,language,region,data_deposited,doi_data_deposited,repository,doi_of_cited_paper,funding
0,0,0,https://doi.org/10.1186/s40862-020-00088-w,A comparative study of the effect of teacher’s...,"Zahra Pourmousavi, Zohre Mohamadi Zenouzagh",Asian-Pacific Journal of Second and Foreign La...,2020.0,tests,"books, scholarly articles",Iran,English,NaN,Upon request,NaN,NaN,NaN,No funding
1,1,1,https://doi.org/10.1186/s40862-020-00081-3,Examining the influence of native and non-nati...,Andrew Schenck,Asian-Pacific Journal of Second and Foreign La...,2020.0,academic essays,"books, scholarly articles","China, Hong Kong, Indonesia, Japan, Korea, Pak...",English,NaN,Although the data used by the researcher was o...,NaN,NaN,NaN,No funding
2,2,2,https://doi.org/10.1186/s40862-021-00118-1,Profiling the pausing behaviour of EFL learner...,"Shen Cuiping, Chen Ningyang",Asian-Pacific Journal of Second and Foreign La...,2021.0,"keystroke logging, screen recording","books, scholarly articles",China,English,NaN,Upon request,NaN,NaN,NaN,No funding
3,3,3,https://doi.org/10.1186/s40862-021-00117-2,Epistemological beliefs and conceptions about ...,"Wanjuan Zhong, Gift Muyunda, Jun Cheng",Asian-Pacific Journal of Second and Foreign La...,2021.0,interviews,"books, scholarly articles",Zambia,Chinese,Mandarin,Upon request,NaN,NaN,NaN,"Chongqing Federation of Social Sciences,"
4,4,4,https://doi.org/10.1186/s40862-021-00116-3,Maltese as a foreign language educators’ acqui...,Jacqueline Żammi,Asian-Pacific Journal of Second and Foreign La...,2021.0,"observation, interviews, text messages\n","books, scholarly articles",Malta,Maltese,NaN,Upon request,NaN,NaN,NaN,No funding

In [ ]:
df["primary_sources"] = df["primary_sources"].str.lower()
df["secondary_sources"] = df["secondary_sources"].str.lower()


df["authors"] = df["authors"].str.replace(",", ";")
df["publication_year"] = df["publication_year"].astype('Int64')


df.head()

,Unnamed: 0.1,Unnamed: 0,doi,title,authors,journal_name,publication_year,primary_sources,secondary_sources,geographic_location,language,region,data_deposited,doi_data_deposited,repository,doi_of_cited_paper,funding
0,0,0,https://doi.org/10.1186/s40862-020-00088-w,A comparative study of the effect of teacher’s...,Zahra Pourmousavi; Zohre Mohamadi Zenouzagh,Asian-Pacific Journal of Second and Foreign La...,2020,tests,"books, scholarly articles",Iran,English,NaN,Upon request,NaN,NaN,NaN,No funding
1,1,1,https://doi.org/10.1186/s40862-020-00081-3,Examining the influence of native and non-nati...,Andrew Schenck,Asian-Pacific Journal of Second and Foreign La...,2020,academic essays,"books, scholarly articles","China, Hong Kong, Indonesia, Japan, Korea, Pak...",English,NaN,Although the data used by the researcher was o...,NaN,NaN,NaN,No funding
2,2,2,https://doi.org/10.1186/s40862-021-00118-1,Profiling the pausing behaviour of EFL learner...,Shen Cuiping; Chen Ningyang,Asian-Pacific Journal of Second and Foreign La...,2021,"keystroke logging, screen recording","books, scholarly articles",China,English,NaN,Upon request,NaN,NaN,NaN,No funding
3,3,3,https://doi.org/10.1186/s40862-021-00117-2,Epistemological beliefs and conceptions about ...,Wanjuan Zhong; Gift Muyunda; Jun Cheng,Asian-Pacific Journal of Second and Foreign La...,2021,interviews,"books, scholarly articles",Zambia,Chinese,Mandarin,Upon request,NaN,NaN,NaN,"Chongqing Federation of Social Sciences,"
4,4,4,https://doi.org/10.1186/s40862-021-00116-3,Maltese as a foreign language educators’ acqui...,Jacqueline Żammi,Asian-Pacific Journal of Second and Foreign La...,2021,"observation, interviews, text messages\n","books, scholarly articles",Malta,Maltese,NaN,Upon request,NaN,NaN,NaN,No funding